<?php

use Drupal\Core\Form;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_id_alter().
 */
function axelerant_assignment_form_system_site_information_settings_alter(&$form, FormStateInterface $form_state, $form_id){
	$site_api_key = \Drupal::config('axelerant_assignment.settings')->get('siteapikey');
	//adding text field for Site API key
	$form['site_information']['siteapikey'] = [
      '#type' => 'textfield',
      '#title' => t('Site Api Key'),
      '#default_value' => $site_api_key ? $site_api_key: 'No API Key yet',
    ];
	// adding validating function to get the siteapikey value to set it in a variable
    $form['#validate'][] = 'axelerant_assignment_form_validation';
	// changing the name of submit button value 
    $form['actions']['submit']['#value'] = t('Update Configuration');
}

/**
 * Implements validation function called inside hook_form_id_alter().
 */
function axelerant_assignment_form_validation(&$form, FormStateInterface $form_state){
	$site_api_key = $form_state->getValue('siteapikey');
	$config = \Drupal::service('config.factory')->getEditable('axelerant_assignment.settings');
	$config->set('siteapikey', $site_api_key)->save(); // saving the site api key to a configuration variable "siteapikey"
    // showing message only if site api key is set with a value
	if(!empty($site_api_key)){
	  drupal_set_message("Site Api key is set with value '$site_api_key'");
    }
}